In [1]:
import pandas as pd
import numpy as np

In [2]:
fy2021 = pd.read_csv("TRK_13139_FY2021.csv")
fy2021

C:\Users\visha\AppData\Local\Temp\ipykernel_1860\3655403620.py:1: DtypeWarning: Columns (4,7,14,16,25,29,38,39,40,41,44,46,50,51,52,55) have mixed types. Specify dtype option on import or set low_memory=False.
  fy2021 = pd.read_csv("TRK_13139_FY2021.csv")

,bcn,country_of_birth,country_of_nationality,ben_date_of_birth,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,...,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1,T_U_VAWA_FLAG
0,(b)(6),CHN,CHN,(b)(6),1981,male,D&R I.P. Law Firm,453745389,108 N Ynez Ave,Monterey Park,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(b)(6),IND,IND,(b)(6),1994,male,ITTECHNICA INC,824530582,1825 W Walnut Hill Ln,Irving,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(b)(6),CAN,CAN,(b)(6),1988,male,"Tesla, Inc.",912197729,3500 Deer Creek Rd,Palo Alto,...,NaN,G,MASTER'S DEGREE,COMPUTER ENGINEERING,125000,007,336111,B,N,NaN
3,(b)(6),PAK,PAK,(b)(6),1993,male,Crorama Inc.,208487164,391 Thor Pl,Brea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(b)(6),IND,IND,(b)(6),1990,male,XENON INFOTEK INC,223816438,2 Kilmer Rd Ste B,Edison,...,NaN,G,MASTER'S DEGREE,COMPUTER SCI,93496,NaN,541511,B,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269419,(b)(6),IND,IND,(b)(6),1992,male,Larsen & Toubro Infotech Limited,223524303,"2035 Lincoln Hwy, Edison Square West",Edison,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269420,(b)(6),IND,IND,(b)(6),1987,male,HCL America Solutions Inc,455639384,330 Potrero Avenue,Sunnyvale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269421,(b)(6),IND,IND,(b)(6),1984,male,"Capgemini America, Inc.",222575929,333 West Wacker Drive,Chicago,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269422,(b)(6),IND,IND,(b)(6),1986,male,"QUEST GLOBAL SERVICE NA, INC",311393419,111 Founders Plz,East Hartford,...,NaN,F,BACHELOR'S DEGREE,TELECOMM ENGRG,91957.0,30.0,541330.0,B,Y,NaN
269423,(b)(6),IND,IND,(b)(6),1980,male,Bristlecone Inc.,770485545,10 Almaden Blvd Ste 600,San Jose,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
null_percentage = fy2021.isnull().mean() * 100

print(null_percentage)

bcn                          0.000000
country_of_birth             0.000000
country_of_nationality       0.000000
ben_date_of_birth            0.000000
ben_year_of_birth            0.000000
gender                       0.000000
employer_name                0.000000
FEIN                         0.000000
mail_addr                    0.000000
city                         0.000000
state                        0.000000
zip                          0.000000
agent_first_name             0.004454
agent_last_name              0.000742
lottery_year                 0.000000
status_type                  0.000000
ben_multi_reg_ind            0.000000
RECEIPT_NUMBER              62.872276
rec_date                    62.872276
FIRST_DECISION              62.916444
first_decision_date         62.916444
i129_employer_name          62.872276
PET_STREET                  62.873389
PET_CITY                    62.872276
PET_STATE                   62.872276
PET_ZIP                     62.872276
REQUESTED_CLASS             62.872276
BASIS_FOR_CLASSIFICATION    62.872276
REQUESTED_ACTION            62.872276
NUMBER_OF_BENEFICIARIES     62.872276
BEN_SEX                     62.880441
BEN_COUNTRY_OF_BIRTH        62.907165
BEN_CURRENT_CLASS           68.070402
JOB_TITLE                   79.204525
DOL_ETA_CASE_NUMBER         63.011090
WORKSITE_STREET             62.873018
WORKSITE_CITY               62.872276
WORKSITE_STATE              62.872276
WORKSITE_ZIP                62.872276
FULL_TIME_IND               99.982555
WAGE_AMT                    99.982555
WAGE_UNIT                   99.982555
valid_from                  64.245205
valid_to                    64.245205
NUM_OF_EMP_IN_US            62.875616
S1Q1A                       62.874131
S1Q1B                       99.982555
BEN_EDUCATION_CODE          62.875987
ED_LEVEL_DEFINITION         62.875987
BEN_PFIELD_OF_STUDY         62.877843
BEN_COMP_PAID               62.873389
DOT_CODE                    64.246689
NAICS_CODE                  62.876730
S3Q1                        62.881555
S4Q1                        64.289744
T_U_VAWA_FLAG               99.982555
dtype: float64

In [4]:
## Removing columns with a lot of nulls and garbage values ##

fy2021.drop(columns=['bcn', 'ben_date_of_birth', 'WAGE_AMT', 'WAGE_UNIT', 'FULL_TIME_IND', 'S1Q1B',
                     'RECEIPT_NUMBER', 'T_U_VAWA_FLAG', 'DOL_ETA_CASE_NUMBER'], inplace=True)
fy2021

,country_of_birth,country_of_nationality,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,state,zip,...,NUM_OF_EMP_IN_US,S1Q1A,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1
0,CHN,CHN,1981,male,D&R I.P. Law Firm,453745389,108 N Ynez Ave,Monterey Park,CA,91754-1680,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND,IND,1994,male,ITTECHNICA INC,824530582,1825 W Walnut Hill Ln,Irving,TX,75038-4453,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CAN,CAN,1988,male,"Tesla, Inc.",912197729,3500 Deer Creek Rd,Palo Alto,CA,94304-1317,...,0,N,G,MASTER'S DEGREE,COMPUTER ENGINEERING,125000,007,336111,B,N
3,PAK,PAK,1993,male,Crorama Inc.,208487164,391 Thor Pl,Brea,CA,92821-4133,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IND,IND,1990,male,XENON INFOTEK INC,223816438,2 Kilmer Rd Ste B,Edison,NJ,08817-2436,...,0,Y,G,MASTER'S DEGREE,COMPUTER SCI,93496,NaN,541511,B,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269419,IND,IND,1992,male,Larsen & Toubro Infotech Limited,223524303,"2035 Lincoln Hwy, Edison Square West",Edison,NJ,08817,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269420,IND,IND,1987,male,HCL America Solutions Inc,455639384,330 Potrero Avenue,Sunnyvale,CA,94085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269421,IND,IND,1984,male,"Capgemini America, Inc.",222575929,333 West Wacker Drive,Chicago,IL,60606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269422,IND,IND,1986,male,"QUEST GLOBAL SERVICE NA, INC",311393419,111 Founders Plz,East Hartford,CT,06108-3289,...,1900.0,Y,F,BACHELOR'S DEGREE,TELECOMM ENGRG,91957.0,30.0,541330.0,B,Y
269423,IND,IND,1980,male,Bristlecone Inc.,770485545,10 Almaden Blvd Ste 600,San Jose,CA,95113-2226,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
fy2021.drop(fy2021[fy2021['ben_multi_reg_ind'] == '(b)(3) (b)(6) (b)(7)(c)'].index, inplace=True)

In [6]:
fy2021 = fy2021.astype({
    'NUM_OF_EMP_IN_US': 'float',
    'ben_year_of_birth': 'int',
    'lottery_year': 'int',
    'ben_multi_reg_ind': 'int',
    'rec_date': 'datetime64[ns]',
    'first_decision_date': 'datetime64[ns]',
    'valid_from': 'datetime64[ns]',
    'valid_to': 'datetime64[ns]',
    'BEN_COMP_PAID': 'float'
})

In [7]:
fy2022 = pd.read_csv("TRK_13139_FY2022.csv")
fy2022

C:\Users\visha\AppData\Local\Temp\ipykernel_1860\430740421.py:1: DtypeWarning: Columns (4,7,14,16,25,29,38,39,40,41,44,46,50,51,52,55) have mixed types. Specify dtype option on import or set low_memory=False.
  fy2022 = pd.read_csv("TRK_13139_FY2022.csv")

,bcn,country_of_birth,country_of_nationality,ben_date_of_birth,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,...,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1,T_U_VAWA_FLAG
0,(b)(6),IND,IND,(b)(6),1991,male,Client Software Services LLC.,460525861,101 Lakeforest Blvd,Gaithersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(b)(6),IND,IND,(b)(6),1995,male,"Primera Technology, Inc.",411899601,2 Carlson Pkwy N Ste 375,Plymouth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(b)(6),IND,IND,(b)(6),1994,male,WIPRO LIMITED,980154401,2 Tower Center Blvd,E Brunswick,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(b)(6),IND,IND,(b)(6),1989,male,SOFTWARE ENTERPRISE LLC,260452051,360 Bloomfield Ave,Windsor,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(b)(6),IND,IND,(b)(6),1991,male,BLOCKCHAIN TECHNOLOGIES LLC,611863670,640 S Pine St,Grand Island,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301442,(b)(6),CHN,CHN,(b)(6),1993,female,"The Club at Las Campanas, Inc.",263558199,132 Clubhouse Drive,Santa Fe,...,NaN,G,MASTER'S DEGREE,HOSPITALITY MANAGEMENT,59600.0,12.0,713910.0,B,N,NaN
301443,(b)(6),IND,IND,(b)(6),1984,male,IMAGEVISION.AI LLC,844349832,5055 Keller Springs Rd,Addison,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301444,(b)(6),IND,IND,(b)(6),1991,male,HCL America Inc,770205035,330 Potrero Avenue,Sunnyvale,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301445,(b)(6),IND,IND,(b)(6),1988,male,Tata Consultancy Services Limited,980429806,9201 Corporate Blvd,Rockville,...,NaN,F,BACHELOR'S DEGREE,COMPUTER SCIENCE,90300.0,30.0,54151.0,B,N,NaN
301446,(b)(6),IND,IND,(b)(6),1988,female,Bits and Binaries Inc,821370788,4425 W Airport Fwy,Irving,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
null_percentage = fy2022.isnull().mean() * 100

print(null_percentage)

bcn                          0.000000
country_of_birth             0.000000
country_of_nationality       0.000000
ben_date_of_birth            0.000000
ben_year_of_birth            0.000000
gender                       0.000000
employer_name                0.000000
FEIN                         0.000000
mail_addr                    0.000000
city                         0.000000
state                        0.000000
zip                          0.000000
agent_first_name             0.056726
agent_last_name              0.119756
lottery_year                 0.000000
status_type                  0.000000
ben_multi_reg_ind            0.000000
RECEIPT_NUMBER              70.168885
rec_date                    70.168885
FIRST_DECISION              70.179501
first_decision_date         70.179501
i129_employer_name          70.168885
PET_STREET                  70.169217
PET_CITY                    70.168885
PET_STATE                   70.169549
PET_ZIP                     70.169549
REQUESTED_CLASS             70.168885
BASIS_FOR_CLASSIFICATION    70.168885
REQUESTED_ACTION            70.168885
NUMBER_OF_BENEFICIARIES     70.168885
BEN_SEX                     70.181491
BEN_COUNTRY_OF_BIRTH        70.206371
BEN_CURRENT_CLASS           75.564859
JOB_TITLE                   82.215116
DOL_ETA_CASE_NUMBER         70.288973
WORKSITE_STREET             70.168885
WORKSITE_CITY               70.168885
WORKSITE_STATE              70.168885
WORKSITE_ZIP                70.168885
FULL_TIME_IND               99.990711
WAGE_AMT                    99.990711
WAGE_UNIT                   99.990711
valid_from                  70.819083
valid_to                    70.819083
NUM_OF_EMP_IN_US            70.170212
S1Q1A                       70.170212
S1Q1B                       99.990711
BEN_EDUCATION_CODE          70.172203
ED_LEVEL_DEFINITION         70.172203
BEN_PFIELD_OF_STUDY         70.173530
BEN_COMP_PAID               70.170876
DOT_CODE                    70.828039
NAICS_CODE                  70.172866
S3Q1                        70.169881
S4Q1                        70.181491
T_U_VAWA_FLAG               99.990711
dtype: float64

In [9]:
## Removing columns with a lot of nulls and garbage values ##

fy2022.drop(columns=['bcn', 'ben_date_of_birth', 'WAGE_AMT', 'WAGE_UNIT', 'FULL_TIME_IND', 'S1Q1B',
                     'RECEIPT_NUMBER', 'T_U_VAWA_FLAG', 'DOL_ETA_CASE_NUMBER'], inplace=True)
fy2022

,country_of_birth,country_of_nationality,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,state,zip,...,NUM_OF_EMP_IN_US,S1Q1A,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1
0,IND,IND,1991,male,Client Software Services LLC.,460525861,101 Lakeforest Blvd,Gaithersburg,MD,20877-2634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND,IND,1995,male,"Primera Technology, Inc.",411899601,2 Carlson Pkwy N Ste 375,Plymouth,MN,55447-4446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND,IND,1994,male,WIPRO LIMITED,980154401,2 Tower Center Blvd,E Brunswick,NJ,08816-1100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND,IND,1989,male,SOFTWARE ENTERPRISE LLC,260452051,360 Bloomfield Ave,Windsor,CT,06095-2700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IND,IND,1991,male,BLOCKCHAIN TECHNOLOGIES LLC,611863670,640 S Pine St,Grand Island,NE,68801-7981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301442,CHN,CHN,1993,female,"The Club at Las Campanas, Inc.",263558199,132 Clubhouse Drive,Santa Fe,NM,87506,...,0.0,N,G,MASTER'S DEGREE,HOSPITALITY MANAGEMENT,59600.0,12.0,713910.0,B,N
301443,IND,IND,1984,male,IMAGEVISION.AI LLC,844349832,5055 Keller Springs Rd,Addison,TX,75001-6911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301444,IND,IND,1991,male,HCL America Inc,770205035,330 Potrero Avenue,Sunnyvale,CA,94085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301445,IND,IND,1988,male,Tata Consultancy Services Limited,980429806,9201 Corporate Blvd,Rockville,MD,20850-6522,...,0.0,Y,F,BACHELOR'S DEGREE,COMPUTER SCIENCE,90300.0,30.0,54151.0,B,N
301446,IND,IND,1988,female,Bits and Binaries Inc,821370788,4425 W Airport Fwy,Irving,TX,75062-5814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
fy2022.drop(fy2022[fy2022['ben_multi_reg_ind'] == '(b)(3) (b)(6) (b)(7)(c)'].index, inplace=True)

In [11]:
fy2022 = fy2022.astype({
    'NUM_OF_EMP_IN_US': 'float',
    'ben_year_of_birth': 'int',
    'lottery_year': 'int',
    'ben_multi_reg_ind': 'int',
    'rec_date': 'datetime64[ns]',
    'first_decision_date': 'datetime64[ns]',
    'valid_from': 'datetime64[ns]',
    'valid_to': 'datetime64[ns]',
    'BEN_COMP_PAID': 'float'
})

In [12]:
fy2023 = pd.read_csv("TRK_13139_FY2023.csv")
fy2023

C:\Users\visha\AppData\Local\Temp\ipykernel_1860\2646576541.py:1: DtypeWarning: Columns (4,7,14,16,29,40,44,50,51,52,55) have mixed types. Specify dtype option on import or set low_memory=False.
  fy2023 = pd.read_csv("TRK_13139_FY2023.csv")

,bcn,country_of_birth,country_of_nationality,ben_date_of_birth,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,...,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1,T_U_VAWA_FLAG
0,(b)(6),IND,IND,(b)(6),1993,male,Kee Technologies Group Inc,204388131,4 Mckissic Creek Rd,Bentonville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(b)(6),IND,IND,(b)(6),1979,male,IBM Corporation,130871985,3039 Cornwallis Rd,Durham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(b)(6),IND,IND,(b)(6),1996,female,Geminisoft Solutions Inc,880817524,800 Stone Bridge Springs Dr.,Wildwood,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(b)(6),IND,IND,(b)(6),1987,female,Infosys Limited,581760235,2400 N Glenville Dr,Richardson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(b)(6),GBR,GBR,(b)(6),1999,male,"Putnam Associates, LLC",463321955,501 Boylston St,Boston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474416,(b)(6),IND,IND,(b)(6),1992,male,GENIEIUM INC,874101544,42712 Ogilvie Sq,Ashburn,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474417,(b)(6),IND,IND,(b)(6),1991,male,"SQL Data Solutions, Inc",262858253,"450 N University Avenue,",Provo,...,N,NaN,NaN,MASTERS IN COMPUTER/INFORMATION TECHNOLOGY SER...,70000.0,NaN,541511.0,B,N,NaN
474418,(b)(6),IND,IND,(b)(6),1991,male,ROBOTIC PROCESS AUTOMATION LLC,371876789,639 S Locust St,Grand Island,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474419,(b)(6),IND,IND,(b)(6),1992,male,SUNRISE TECHNOLOGIES LLC,320615787,640 S Pine St,Grand Island,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474420,(b)(6),IND,IND,(b)(6),1983,male,"KVK-Tech, Inc.",200066907,110 Terry Dr,Newtown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
null_percentage = fy2023.isnull().mean() * 100

print(null_percentage)

bcn                          0.000000
country_of_birth             0.000000
country_of_nationality       0.000000
ben_date_of_birth            0.000000
ben_year_of_birth            0.000000
gender                       0.000000
employer_name                0.000000
FEIN                         0.000000
mail_addr                    0.000000
city                         0.000000
state                        0.000000
zip                          0.000000
agent_first_name             0.055436
agent_last_name              0.210362
lottery_year                 0.000000
status_type                  0.000000
ben_multi_reg_ind            0.000000
RECEIPT_NUMBER              80.125037
rec_date                    80.125037
FIRST_DECISION              80.160448
first_decision_date         80.160448
i129_employer_name          80.125669
PET_STREET                  80.125247
PET_CITY                    80.125037
PET_STATE                   80.125037
PET_ZIP                     80.125458
REQUESTED_CLASS             80.126301
BASIS_FOR_CLASSIFICATION    80.126301
REQUESTED_ACTION            80.125037
NUMBER_OF_BENEFICIARIES     80.570211
BEN_SEX                     80.125037
BEN_COUNTRY_OF_BIRTH        80.125037
BEN_CURRENT_CLASS           85.457220
JOB_TITLE                   85.083291
DOL_ETA_CASE_NUMBER         80.635554
WORKSITE_STREET             80.129252
WORKSITE_CITY               80.148012
WORKSITE_STATE              80.147169
WORKSITE_ZIP                80.145693
FULL_TIME_IND               89.611126
WAGE_AMT                    80.175414
WAGE_UNIT                   80.172674
valid_from                  80.816195
valid_to                    80.816195
NUM_OF_EMP_IN_US            80.488216
S1Q1A                       80.272585
S1Q1B                       87.291035
BEN_EDUCATION_CODE          87.643886
ED_LEVEL_DEFINITION         87.643886
BEN_PFIELD_OF_STUDY         80.152649
BEN_COMP_PAID               80.705534
DOT_CODE                    80.476834
NAICS_CODE                  80.171198
S3Q1                        80.125880
S4Q1                        80.125247
T_U_VAWA_FLAG               99.992201
dtype: float64

In [14]:
## Removing columns with a lot of nulls and garbage values ##

fy2023.drop(columns=['RECEIPT_NUMBER', 'bcn', 'ben_date_of_birth', 'T_U_VAWA_FLAG', 'DOL_ETA_CASE_NUMBER'], inplace=True)
fy2023

,country_of_birth,country_of_nationality,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,state,zip,...,S1Q1A,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1
0,IND,IND,1993,male,Kee Technologies Group Inc,204388131,4 Mckissic Creek Rd,Bentonville,AR,72712-8901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND,IND,1979,male,IBM Corporation,130871985,3039 Cornwallis Rd,Durham,NC,27709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND,IND,1996,female,Geminisoft Solutions Inc,880817524,800 Stone Bridge Springs Dr.,Wildwood,MO,63005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND,IND,1987,female,Infosys Limited,581760235,2400 N Glenville Dr,Richardson,TX,75082,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GBR,GBR,1999,male,"Putnam Associates, LLC",463321955,501 Boylston St,Boston,MA,02116,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474416,IND,IND,1992,male,GENIEIUM INC,874101544,42712 Ogilvie Sq,Ashburn,VA,20148-4182,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474417,IND,IND,1991,male,"SQL Data Solutions, Inc",262858253,"450 N University Avenue,",Provo,UT,84601,...,N,N,NaN,NaN,MASTERS IN COMPUTER/INFORMATION TECHNOLOGY SER...,70000.0,NaN,541511.0,B,N
474418,IND,IND,1991,male,ROBOTIC PROCESS AUTOMATION LLC,371876789,639 S Locust St,Grand Island,NE,68801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474419,IND,IND,1992,male,SUNRISE TECHNOLOGIES LLC,320615787,640 S Pine St,Grand Island,NE,68801,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474420,IND,IND,1983,male,"KVK-Tech, Inc.",200066907,110 Terry Dr,Newtown,PA,18940-3427,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
fy2023.drop(fy2023[fy2023['ben_multi_reg_ind'] == '(b)(3) (b)(6) (b)(7)(c)'].index, inplace=True)

In [16]:
fy2023['BEN_COMP_PAID'] = fy2023['BEN_COMP_PAID'].replace(',', '', regex=True)

In [17]:
fy2023 = fy2023.astype({
    'NUM_OF_EMP_IN_US': 'float',
    'ben_year_of_birth': 'int',
    'lottery_year': 'int',
    'ben_multi_reg_ind': 'int',
    'rec_date': 'datetime64[ns]',
    'first_decision_date': 'datetime64[ns]',
    'valid_from': 'datetime64[ns]',
    'valid_to': 'datetime64[ns]',
    'BEN_COMP_PAID': 'float'
})

In [18]:
fy2024_1 = pd.read_csv("TRK_13139_FY2024_single_reg.csv")
fy2024_1

C:\Users\visha\AppData\Local\Temp\ipykernel_1860\1834714074.py:1: DtypeWarning: Columns (4,7,14,16,29,40,44,50,51,52,55) have mixed types. Specify dtype option on import or set low_memory=False.
  fy2024_1 = pd.read_csv("TRK_13139_FY2024_single_reg.csv")

,bcn,country_of_birth,country_of_nationality,ben_date_of_birth,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,...,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1,T_U_VAWA_FLAG
0,(b)(6),IND,IND,(b)(6),1994,male,Mphasis Corporation,954759720,41 Madison Ave,New York,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(b)(6),KOR,KOR,(b)(6),1994,male,"Tennessee Dental Professionals, PC",200418100,1200 Network Centre Drive,Effingham,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(b)(6),IND,IND,(b)(6),1982,male,KPMG LLP,135565207,2323 Ross Ave,Dallas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(b)(6),IND,IND,(b)(6),1995,male,3D TECHNOLOGIES LLC,384053952,423 W Wheatland Rd,Duncanville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(b)(6),GHA,GHA,(b)(6),1990,male,"LER TechForce, LLC",352139176,1888 Poshard Drive,Columbus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350098,(b)(6),CHN,CHN,(b)(6),1987,male,Google LLC,770493581,1600 Amphitheatre Parkway,Mountain View,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350099,(b)(6),GBR,IRL,(b)(6),1989,male,KLA Corporation,42564110,One Technology Drive,Milpitas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350100,(b)(6),CHN,CHN,(b)(6),2000,female,Deloitte & Touche LLP,133891517,1700 Market Street,Philadelphia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350101,(b)(6),IND,IND,(b)(6),1987,male,PRIAMBA SOFT LLC,462435519,"517 Us Highway 1 S, Suite 1193",Iselin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350102,(b)(6),IND,IND,(b)(6),1984,male,"BrightFonts, Inc.",472246802,222 West Las Colinas Blvd,Irving,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
null_percentage = fy2024_1.isnull().mean() * 100

print(null_percentage)

bcn                          0.000000
country_of_birth             0.000000
country_of_nationality       0.000000
ben_date_of_birth            0.000000
ben_year_of_birth            0.000000
gender                       0.000000
employer_name                0.000286
FEIN                         0.000000
mail_addr                    0.000000
city                         0.000000
state                        0.000000
zip                          0.000000
agent_first_name             0.014853
agent_last_name              0.046558
lottery_year                 0.000000
status_type                  0.000000
ben_multi_reg_ind            0.000000
RECEIPT_NUMBER              80.339214
rec_date                    80.339214
FIRST_DECISION              80.457751
first_decision_date         80.457751
i129_employer_name          80.339214
PET_STREET                  80.339214
PET_CITY                    80.339214
PET_STATE                   80.339214
PET_ZIP                     80.339500
REQUESTED_CLASS             80.340071
BASIS_FOR_CLASSIFICATION    80.340071
REQUESTED_ACTION            80.339214
NUMBER_OF_BENEFICIARIES     80.827642
BEN_SEX                     80.339214
BEN_COUNTRY_OF_BIRTH        80.339214
BEN_CURRENT_CLASS           84.950715
JOB_TITLE                   85.625087
DOL_ETA_CASE_NUMBER         80.439471
WORKSITE_STREET             80.341785
WORKSITE_CITY               80.358637
WORKSITE_STATE              80.357209
WORKSITE_ZIP                80.357495
FULL_TIME_IND               87.861287
WAGE_AMT                    80.384058
WAGE_UNIT                   80.381202
valid_from                  80.701679
valid_to                    80.701679
NUM_OF_EMP_IN_US            80.890481
S1Q1A                       80.343213
S1Q1B                       85.526831
BEN_EDUCATION_CODE          86.672494
ED_LEVEL_DEFINITION         86.672494
BEN_PFIELD_OF_STUDY         80.362922
BEN_COMP_PAID               80.779371
DOT_CODE                    80.411193
NAICS_CODE                  80.366064
S3Q1                        80.339786
S4Q1                        80.339214
T_U_VAWA_FLAG               99.994573
dtype: float64

In [20]:
## Removing columns with a lot of nulls and garbage values ##

fy2024_1.drop(columns=['bcn', 'ben_date_of_birth', 'T_U_VAWA_FLAG', 'DOL_ETA_CASE_NUMBER', 'RECEIPT_NUMBER'], inplace=True)
fy2024_1

,country_of_birth,country_of_nationality,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,state,zip,...,S1Q1A,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1
0,IND,IND,1994,male,Mphasis Corporation,954759720,41 Madison Ave,New York,NY,10010-2208,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,KOR,KOR,1994,male,"Tennessee Dental Professionals, PC",200418100,1200 Network Centre Drive,Effingham,IL,62401,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND,IND,1982,male,KPMG LLP,135565207,2323 Ross Ave,Dallas,TX,75201-2721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND,IND,1995,male,3D TECHNOLOGIES LLC,384053952,423 W Wheatland Rd,Duncanville,TX,75116-4605,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GHA,GHA,1990,male,"LER TechForce, LLC",352139176,1888 Poshard Drive,Columbus,IN,47203,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350098,CHN,CHN,1987,male,Google LLC,770493581,1600 Amphitheatre Parkway,Mountain View,CA,94043,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350099,GBR,IRL,1989,male,KLA Corporation,42564110,One Technology Drive,Milpitas,CA,95035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350100,CHN,CHN,2000,female,Deloitte & Touche LLP,133891517,1700 Market Street,Philadelphia,PA,19103-3913,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350101,IND,IND,1987,male,PRIAMBA SOFT LLC,462435519,"517 Us Highway 1 S, Suite 1193",Iselin,NJ,08830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
350102,IND,IND,1984,male,"BrightFonts, Inc.",472246802,222 West Las Colinas Blvd,Irving,TX,75039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
fy2024_1.drop(fy2024_1[fy2024_1['ben_multi_reg_ind'] == '(b)(3) (b)(6) (b)(7)(c)'].index, inplace=True)

In [22]:
fy2024_1['BEN_COMP_PAID'] = fy2024_1['BEN_COMP_PAID'].replace(',', '', regex=True)

In [23]:
fy2024_1 = fy2024_1.astype({
    'NUM_OF_EMP_IN_US': 'float',
    'ben_year_of_birth': 'int',
    'lottery_year': 'int',
    'ben_multi_reg_ind': 'int',
    'rec_date': 'datetime64[ns]',
    'first_decision_date': 'datetime64[ns]',
    'valid_from': 'datetime64[ns]',
    'valid_to': 'datetime64[ns]',
    'BEN_COMP_PAID': 'float'
})

In [24]:
fy2024_2 = pd.read_csv("TRK_13139_FY2024_multi_reg.csv")
fy2024_2

C:\Users\visha\AppData\Local\Temp\ipykernel_1860\3733278726.py:1: DtypeWarning: Columns (4,7,14,16,29,40,44,50,51,52,55) have mixed types. Specify dtype option on import or set low_memory=False.
  fy2024_2 = pd.read_csv("TRK_13139_FY2024_multi_reg.csv")

,bcn,country_of_birth,country_of_nationality,ben_date_of_birth,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,...,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1,T_U_VAWA_FLAG
0,(b)(6),IND,NOR,(b)(6),1985,female,Lancesoft Inc.,541974095,2121 Cooperative Way,Herndon,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(b)(6),IND,IND,(b)(6),1997,male,Itechmatics Inc,260397463,600 W Santa Ana Blvd,Santa Ana,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(b)(6),IND,IND,(b)(6),1995,male,Dataquad Inc.,471729855,2000 S Dairy Ashford Rd Ste 405,Houston,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(b)(6),IND,IND,(b)(6),1980,male,Mejenta Systems Inc,200388168,30233 Southfield Rd,Southfield,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(b)(6),IND,IND,(b)(6),1991,male,Codersdoor LLC,871109906,1431 Greenway Drive,Irving,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408886,(b)(6),IND,IND,(b)(6),1997,female,MERIDIANSOFT INC,203045751,615 Carle Ave,Lewis Center,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408887,(b)(6),IND,IND,(b)(6),1997,male,NerdPine Solutions LLC,822199803,1849 Ne 106th Avenue,Hillsboro,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408888,(b)(6),IND,IND,(b)(6),1992,male,INFODATAWORX LLC,872163342,10829 Sexton Dr,Mckinney,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408889,(b)(6),IND,IND,(b)(6),1992,female,"I Brain Solutions, LLC",208337679,1340 Stelton Rd,Piscataway,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408890,(b)(6),IND,IND,(b)(6),1991,male,"Cyber Infotech, LLC",141960164,438 North Frederick Avenue,Gaithersburg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
null_percentage = fy2024_2.isnull().mean() * 100

print(null_percentage)

bcn                          0.000000
country_of_birth             0.000000
country_of_nationality       0.000000
ben_date_of_birth            0.000000
ben_year_of_birth            0.000000
gender                       0.000000
employer_name                0.000000
FEIN                         0.000000
mail_addr                    0.000000
city                         0.000000
state                        0.000000
zip                          0.000000
agent_first_name             0.022989
agent_last_name              0.272444
lottery_year                 0.000000
status_type                  0.000000
ben_multi_reg_ind            0.000000
RECEIPT_NUMBER              94.244676
rec_date                    94.244676
FIRST_DECISION              94.448643
first_decision_date         94.448643
i129_employer_name          94.244676
PET_STREET                  94.244676
PET_CITY                    94.244676
PET_STATE                   94.244676
PET_ZIP                     94.244676
REQUESTED_CLASS             94.244676
BASIS_FOR_CLASSIFICATION    94.244676
REQUESTED_ACTION            94.244676
NUMBER_OF_BENEFICIARIES     94.401931
BEN_SEX                     94.244676
BEN_COUNTRY_OF_BIRTH        94.244676
BEN_CURRENT_CLASS           96.384366
JOB_TITLE                   95.789098
DOL_ETA_CASE_NUMBER         94.275002
WORKSITE_STREET             94.247122
WORKSITE_CITY               94.254704
WORKSITE_STATE              94.254948
WORKSITE_ZIP                94.253725
FULL_TIME_IND               96.476323
WAGE_AMT                    94.259595
WAGE_UNIT                   94.258617
valid_from                  94.696386
valid_to                    94.696386
NUM_OF_EMP_IN_US            94.316578
S1Q1A                       94.245410
S1Q1B                       96.684202
BEN_EDUCATION_CODE          96.040999
ED_LEVEL_DEFINITION         96.040999
BEN_PFIELD_OF_STUDY         94.257149
BEN_COMP_PAID               94.453290
DOT_CODE                    94.260084
NAICS_CODE                  94.257394
S3Q1                        94.245410
S4Q1                        94.244676
T_U_VAWA_FLAG               99.998043
dtype: float64

In [26]:
## Removing columns with a lot of nulls and garbage values ##

fy2024_2.drop(columns=['RECEIPT_NUMBER', 'bcn', 'ben_date_of_birth', 'T_U_VAWA_FLAG', 'DOL_ETA_CASE_NUMBER'], inplace=True)
fy2024_2

,country_of_birth,country_of_nationality,ben_year_of_birth,gender,employer_name,FEIN,mail_addr,city,state,zip,...,S1Q1A,S1Q1B,BEN_EDUCATION_CODE,ED_LEVEL_DEFINITION,BEN_PFIELD_OF_STUDY,BEN_COMP_PAID,DOT_CODE,NAICS_CODE,S3Q1,S4Q1
0,IND,NOR,1985,female,Lancesoft Inc.,541974095,2121 Cooperative Way,Herndon,VA,20171-5370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IND,IND,1997,male,Itechmatics Inc,260397463,600 W Santa Ana Blvd,Santa Ana,CA,92701-4514,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IND,IND,1995,male,Dataquad Inc.,471729855,2000 S Dairy Ashford Rd Ste 405,Houston,TX,77077-5727,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IND,IND,1980,male,Mejenta Systems Inc,200388168,30233 Southfield Rd,Southfield,MI,48076-1362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IND,IND,1991,male,Codersdoor LLC,871109906,1431 Greenway Drive,Irving,TX,75038,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408886,IND,IND,1997,female,MERIDIANSOFT INC,203045751,615 Carle Ave,Lewis Center,OH,43035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408887,IND,IND,1997,male,NerdPine Solutions LLC,822199803,1849 Ne 106th Avenue,Hillsboro,OR,97006,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408888,IND,IND,1992,male,INFODATAWORX LLC,872163342,10829 Sexton Dr,Mckinney,TX,75072-3307,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408889,IND,IND,1992,female,"I Brain Solutions, LLC",208337679,1340 Stelton Rd,Piscataway,NJ,08854-5206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408890,IND,IND,1991,male,"Cyber Infotech, LLC",141960164,438 North Frederick Avenue,Gaithersburg,MD,20877,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
fy2024_2.drop(fy2024_2[fy2024_2['ben_multi_reg_ind'] == '(b)(3) (b)(6) (b)(7)(c)'].index, inplace=True)

In [28]:
fy2024_2['BEN_COMP_PAID'] = fy2024_2['BEN_COMP_PAID'].replace(',', '', regex=True)

In [29]:
fy2024_2 = fy2024_2.astype({
    'NUM_OF_EMP_IN_US': 'float',
    'ben_year_of_birth': 'int',
    'lottery_year': 'int',
    'ben_multi_reg_ind': 'int',
    'rec_date': 'datetime64[ns]',
    'first_decision_date': 'datetime64[ns]',
    'valid_from': 'datetime64[ns]',
    'valid_to': 'datetime64[ns]',
    'BEN_COMP_PAID': 'float'
})

In [30]:
fy2021.to_csv('FY2021.csv', index=False)
fy2022.to_csv('FY2022.csv', index=False)
fy2023.to_csv('FY2023.csv', index=False)
fy2024_1.to_csv('FY2024_part1.csv', index=False)
fy2024_2.to_csv('FY2024_part2.csv', index=False)